### PR TITLE
Add summary endpoint

### PR DESCRIPTION
**Pull request by barthalion**

### CODE REVIEW

**Comment by barthalion** [comment]
Example response with real life data:

```
{
  "arches": [
    "aarch64",
    "arm",
    "i386",
    "x86_64"
  ],
  "timestamp": 1606832603,
  "download_size": 35991040,
  "installed_size": 12832449,
  "metadata": {
    "Application": {
      "name": "org.vim.Vim",
      "runtime": "org.freedesktop.Platform/x86_64/20.08",
      "sdk": "org.freedesktop.Sdk/x86_64/20.08",
      "command": "vim"
    },
    "Context": {
      "shared": "network;ipc;",
      "sockets": "x11;wayland;",
      "filesystems": "/var/tmp;/tmp;host;"
    },
    "Session Bus Policy": {
      "org.freedesktop.flatpak": "talk"
    },
    "Build": {
      "built-extensions": "org.vim.Vim.Sources;"
    }
  }
}
```

Current `metadata` is basically ini→dict conversion; should we sugar-coat it for easier ingestion on the frontend?

**Comment by tchx84** [comment]
> Current `metadata` is basically ini→dict conversion; should we sugar-coat it for easier ingestion on the frontend?

You mean something like this?

```json
{
   "Info": {
       "name": "org.vim.Vim",
       "runtime": "org.freedesktop.Platform/x86_64/20.08",
       "sdk": "org.freedesktop.Sdk/x86_64/20.08",
       "command": "vim"
    },
    "Permissions": {
        "shared": [
           "network",
           "ipc"
        ],
        "sockets": [
            "x11",
            "wayland"
        ],
        "filesystems": [
            "/var/tmp",
            "/tmp",
            "host"
        ],
        "dbus-session-talk": [
            "org.freedesktop.flatpak"
        ]
    },
    "Extensions": [
       "org.vim.Vim.Sources"
     ]
}
```

It could save some work on the front-end, if we transpose into something like that.

**Comment by barthalion** [comment]
Example response after changes:

```
{
  "arches": [
    "x86_64"
  ],
  "timestamp": 1610366023,
  "download_size": 139776,
  "installed_size": 45977683,
  "metadata": {
    "name": "us.zoom.Zoom",
    "runtime": "org.freedesktop.Platform/x86_64/20.08",
    "sdk": "org.freedesktop.Sdk/x86_64/20.08",
    "tags": [
      "proprietary"
    ],
    "command": "zoom",
    "permissions": {
      "shared": [
        "network",
        "ipc"
      ],
      "sockets": [
        "x11",
        "pulseaudio"
      ],
      "devices": [
        "all"
      ],
      "filesystems": [
        "~/Documents/Zoom:create",
        "~/.zoom:create"
      ],
      "session-bus": {
        "talk": [
          "org.gnome.shell",
          "org.freedesktop.screensaver"
        ],
        "own": [
          "org.kde.*"
        ]
      }
    },
    "built-extensions": [
      "us.zoom.Zoom.Sources"
    ],
    "extra-data": {
      "name": "zoom.tar.xz",
      "checksum": "0fdb70aeef9635e7d7d113aa9f293d233939ef9db003234b12d2854995bf4444",
      "size": "45850484",
      "uri": "https://d11yldzmag5yn.cloudfront.net/prod/5.4.57862.0110/zoom_x86_64.tar.xz"
    }
  }
}
```

**Comment by tchx84** [comment]
> Example response after changes:

Pretty :)

**Comment by barthalion** [comment]
@tchx84 Landed tests. If you have no other comments, please merge when you have a minute. Thanks!

**Comment by tchx84** [comment]
> @tchx84 Landed tests. If you have no other comments, please merge when you have a minute. Thanks!

will do!

**Review by tchx84 — APPROVED** [review]

**Pull request merged**
