### PR TITLE
main: Split non-endpoint bits out

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@barthalion this is a _very_ RAW first step, only meant to trigger this conversation.

**Comment by barthalion** [comment]
No complaints, looks great to me. I'll owe you so many beers when this COVID thing is over.

**Comment by tchx84** [comment]
> No complaints, looks great to me. I'll owe you so many beers when this COVID thing is over.

Alright! I will add a few more tests tonight to triple check, then we can merge it. After this, we can start cleaning up code separately.

**Comment by tchx84** [comment]
@barthalion added more detailed tests (luckily, because I catched a regression that way) and this should be ready now.

**Pull request merged**
