### PR TITLE
Implement /popular endpoint

### LINKED ISSUE #19: Add /popular endpoint
The popular section in Angular frontend is crafted manually, based on the number of page views from Google Analytics/Matomo.

After @nedrichards:

>  1. Make popular apps  driven by actual app updates and installs and make the list update automatically and regularly. Limit the category to the top 20 or 30 results (approx 2% of the total app base) which should ensure that these items are actually popular.
>    - Consideration – examine a listing that does/does not include deltas
>    - Ensure that we can calculate a ‘per arch’ version of this list, for when we have a filtered version of the website (given light traffic in some architectures we should experiment with both a combined list that is filtered by architecture availability as well as a listing that is just built from per architecture popularity)
>  2. Have a method to randomise the returned apps within the category to make sure that the front page appears to be visually different on most page loads, whilst also containing recognisable apps.

### PR DESCRIPTION
**Pull request by gasinvein**
Closes #19

I'm not familiar with flathub backend structure, so feel free to correct me if I got something wrong.

Currently this implementation
- Downloads daily flathub stats .json on demand and caches it in Redis
- Sorts apps based on non-delta download count (all dls minus delta dls); I believe delta downloads are irrelevant for popularity counting, since their amount depends more on update frequency
- Return a plain list of top 30 app IDs most popular during given time period

### CODE REVIEW

**Comment by barthalion** [comment]
Needs a rebase due to my overzealous vim config, sorry. Mind adding a test for some specific dates too?

This is in general in line with what I planned to implement. The only thing I'm not sure about whether it makes sense to make dates arbitrary, something like 7 and 30 days sound reasonable to me.

@tchx84 thoughts?

**Comment by gasinvein** [comment]
>Mind adding a test for some specific dates too?

If you consider this approach valid in general - sure, will do.

>I'm not sure about whether it makes sense to make dates arbitrary

Should I just remove routes with dates, then? They're easy to re-add, if proven to make sense.

**Comment by tchx84** [comment]
> Needs a rebase due to my overzealous vim config, sorry. Mind adding a test for some specific dates too?
> 

Yes,  @gasinvein please include tests !

> This is in general in line with what I planned to implement. The only thing I'm not sure about whether it makes sense to make dates arbitrary, something like 7 and 30 days sound reasonable to me.
> 
> @tchx84 thoughts?

Besides my own personal usual nerdy curiosity, I can't really see a use case for arbitrary date ranges. Like @barthalion said, something like "days: int" would be enough.

Then you would just do something like:

```python
    now = datetime.now()
    days_ago = now - timedelta(days=days)

    # range
    start = days_ago
    end = now
```

**Comment by barthalion** [comment]
On that note, Nick also wrote some notes on categories/section on the main page here: https://cloud.gnome.org/s/bfMr6J83Asrycwz

**Comment by gasinvein** [comment]
>a use case for arbitrary date ranges.

Maybe to see how trends changed? E.g. popular this month vs. popular last month.

**Comment by barthalion** [comment]
Probably a good fit for the future™ `/stats` endpoint, but `/popular` was strictly about providing data for currently hard-coded popular apps on the main page.

**Comment by gasinvein** [comment]
Meeh, it took some time for me to get `/update` endpoint working during local tests run. It appears that the second connection to github (downloading picks `apps.json`) hangs. Using `requests.Session` helped.

**Comment by barthalion** [comment]
Feel free to change it as part of this PR. It's weird as it worked for me before but I'm fine with it.

**Comment by gasinvein** [comment]
Added a minimal test case. It only check that `/popular` endpoint works at all. I guess we'll want something more complex, e.g. check if sorting algorithm does what's expected?

**Pull request merged**
