### PR TITLE
Picks endpoints

### PR DESCRIPTION
**Pull request by tchx84**
Depends on https://github.com/flathub/backend/pull/6 (please, merge that first).

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I think the api endpoint should just expose the app-id's instead of the current output

**Comment by tchx84** [comment]
> I think the api endpoint should just expose the app-id's instead of the current output

what exactly is expected to be done with the appids?

**Comment by bilelmoussaoui** [comment]
We will then do a call to get the whole app details, those calls won't be expensive at all for the frontend as we are using server side rendering, so the calls are done once and a static json will be generated from it & used on the website.

**Comment by tchx84** [comment]
> We will then do a call to get the whole app details, those calls won't be expensive at all for the frontend as we are using server side rendering, so the calls are done once and a static json will be generated from it & used on the website.

Are these app details different from what is currently being returned?

Is the server-side rendering bits accessing redis directly? Or does it need to hit the backend again?

**Comment by bilelmoussaoui** [comment]
It does call the API as any consumer. Its the calls won't be per user but per build that would be automatically run for each new publish job.

And the details are not really different,  yes.

**Comment by tchx84** [comment]
> It does call the API as any consumer. Its the calls won't be per user but per build that would be automatically run for each new publish job.
> 
> And the details are not really different, yes.

Shouldn't we then just skip all those jumps? (e.g. less points of failure)

As it is implemented now, it doesn't really matter if is called per-user or just once during the publish job, is just an endpoint that provides the information you need, in a format that is consistent with other app-related endpoints.

Unless there's a specific reason for providing only the appids that I am missing, I believe we should keep it like this (my opinion).

I leave the last call to you guys :+1:

**Comment by bilelmoussaoui** [comment]
Sure, that can work as well :) I just mentioned that we don't explicitly need all the information at once

**Comment by tchx84** [comment]
@bilelmoussaoui @barthalion only-appids now ;)

**Comment by barthalion** [comment]
Looks good. Can you move it to `v2` endpoint? I think it would be nice to make a clean cut between endpoints returning only IDs and ones returning custom data for Angular.

**Comment by tchx84** [comment]
@barthalion done!

**Comment by tchx84** [comment]
@barthalion removed `/apps/` from endpoint.

**Pull request merged**
